### ISSUE TITLE
Squash event title bug

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-chrome-ext#9] opened 2017-03-04 23:37 UTC
Example: If a title is imported and formatted perfectly by the plug-in and doesn't need manual editing, the form does not seem to recognize that the field has any entry at all.

**Comment by aaghevli** [comment] 2017-03-05 01:03
Seeing differences in the HTML when I edit by hand:

Unedited
```
class="form-control ng-pristine ng-empty ng-invalid ng-invalid-required ng-touched"
```

Edited
```
class="form-control ng-touched ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required"
```

**Comment by InciteDemocracy** [comment] 2017-03-06 09:10
@thenoseman If I'm not mistaken you are an expert at making chrome plugins that fill forms! Do you know a way to make a form recognize that data has been entered to a field? We figured out how to get the data into the form, but the form doesn't seem to "know it's there" thanks for taking a look! 

https://github.com/ResistanceCalendar/resistance-calendar-chrome-ext/blob/master/tockify_form_filler.js

The form we are trying to fill out is here:

http://calendar.resistancecalendar.org/tkf2/submitEvent/cd54742f0b5e4bc3987f57056206591c

**Comment by thenoseman** [comment] 2017-03-06 19:42
Hi @InciteDemocracy ,

looks like the app is based on angular1. I also had my share of "fun" filling such forms.

Actually I *didn't* come up with a solution :(

I tried:
- Setting classes on the element like those above.
- Accessing the ng1 root node and removing all validations.

The problem is that the validation are attached to the form elements when ng1 "boots".

Sorry, no solution from me.

**Comment by aaghevli** [comment] 2017-03-06 20:17
Thanks @thenoseman ! I asked around and it turned out I needed to fire an event on the fields:

https://github.com/ResistanceCalendar/resistance-calendar-chrome-ext/commit/b50dde0bdf09d4a242c188a4beda4bb684e0adca

All of them seem to work except for the large rich edit field which is an embedded iFrame, but I guess they said they usually need to clean that up in the process anyway so we may be okay for now?

```
window.frames[0].document.dispatchEvent(new Event('change'));
window.frames[0].document.body.dispatchEvent(new Event('change'));
```

**Comment by aaghevli** [comment] 2017-03-07 07:05
Going to close this. The notes section still does not work, but we can reopen should we need to.

**Closed as completed** 2017-03-07 07:05 UTC
